package constants

const ERROR = "error"

// ARCHETYPE SUBSCRIPTION CONTANTS
const SUBSCRIPTION_NAME = "SUBSCRIPTION_NAME"
const SUSBCRIPTION_SIGNAL_BROKEN = "SUSBCRIPTION_SIGNAL_BROKEN"

const DOT_HTML = ".html"
const DOT_CSS = ".css"
