# .gitlab-ci.yml

# Define the stages of the CI/CD pipeline
stages:
  - build
  - test

# Job for building the Go application
build:
  stage: build
  image: golang:latest
  
  before_script:
    - go version
    - go get -v -t -d ./...

  script:
    - go build -v ./...

# Job for running tests
test:
  stage: test
  image: golang:latest
  
  before_script:
    - go version
    - go get -v -t -d ./...

  script:
    - go test -v ./...